apiVersion: v1
kind: Service

metadata:
  name: automationproject-service

spec:
  selector:
    app: automationproject

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: ClusterIP